#!/bin/bash

scp .pio/build/nanoatmega328/firmware.hex pi@domusbox:/home/pi/tmp/arduino_build
curl http://192.168.1.52/activapi/api/node/toggle/off
ssh pi@domusbox '/home/pi/arduiload firmware.hex'
curl http://192.168.1.52/activapi/api/node/toggle/on
