#!/bin/bash
export $(grep -v '^#' .env | xargs)
scp .pio/build/nanoatmega328/firmware.hex $REMOTE_USER@$REMOTE_HOST:$BUILD_DIR &&
curl $BEFORE_SEND &&
$REMOTE_USER@$REMOTE_HOST "$ARDUINO_UPLOAD firmware.hex" &&
curl $AFTER_SEND
